fix: [cp] destination host wouldn't use ``IGNORE_ERRORS`` and would hide psql errors

diff --git a/bin/pgm b/bin/pgm
--- a/bin/pgm
+++ b/bin/pgm
@@ -499,8 +499,8 @@ host_pg_fill() {
         $pipe |
         (sleep 0.3; pv -i 0.2 -cN unpacked) | buffer -m 8M |
         (sleep 0.5; pv -fi 0.2 -cN fill) |
-        (echo '\\set ON_ERROR_STOP on'; cat) |
-          \$prefix_pg_local_command psql \$pg_local_opts \"$db\" 2>&1 >/dev/null
+        ([ '$IGNORE_ERRORS' ] || echo '\\set ON_ERROR_STOP on'; cat) |
+          \$prefix_pg_local_command psql \$pg_local_opts \"$db\" 2>&1
          )
         errlvl=\"\$?\"
         if [ \"\$errlvl\" == "0" -a -z \"\$output\" ]; then
